name: Tests

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get fonts
      run: |
        mkdir ./tests/fonts/
        ./tests/get-fonts.sh
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test
